### ISSUE TITLE
Running Kedro-docker's kedro docker --help with kedo 0.16.4 returns deprecation warnings for kedro.cli

### ISSUE THREAD

**Issue by javierabosch** [quantumblacklabs/kedro-docker#39]
Should Kedro docker be updated with the kedro.framework.cli inside kedro_docker/ . So far I noticed plugin.py and helpers.py

**Comment by DmitriiDeriabinQB** [comment]
@javierabosch Thank you, good point 👍 I will address this in the PR linked above.
