### ISSUE TITLE
Lightweight & Secure Docker Image

### ISSUE THREAD

**Issue by yarncraft** [quantumblacklabs/kedro-docker#5]
## Description
As I stated in an earlier PR, in order to reduce the Docker Image, you might opt for deploying PySpark and Hadoop on a security-oriented / lightweight Linux distribution called Alpine. Working with data could always incur big risks, I therefore suggest to check out: https://snyk.io/blog/10-docker-image-security-best-practices/, these principles are easy to apply and harden data security/integrity, as data leaks could be potentially harmful when working with customer data.

## Context
The lightweight OS together with miniconda could reduce the image-size by up to 80%, resulting in significantly faster builds. 

## Possible Implementation
```Dockerfile
FROM openjdk:8-jdk-alpine

ENV HADOOP_VERSION 2.7.3
ENV HADOOP_HOME /usr/hadoop-$HADOOP_VERSION
ENV HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop

ENV SPARK_VERSION 2.3.2
ENV SPARK_PACKAGE spark-${SPARK_VERSION}-bin-without-hadoop
ENV SPARK_HOME /usr/spark-${SPARK_VERSION}
ENV SPARK_DIST_CLASSPATH="$HADOOP_HOME/etc/hadoop/*:$HADOOP_HOME/share/hadoop/common/lib/*:$HADOOP_HOME/share/hadoop/common/*:$HADOOP_HOME/share/hadoop/hdfs/*:$HADOOP_HOME/share/hadoop/hdfs/lib/*:$HADOOP_HOME/share/hadoop/hdfs/*:$HADOOP_HOME/share/hadoop/yarn/lib/*:$HADOOP_HOME/share/hadoop/yarn/*:$HADOOP_HOME/share/hadoop/mapreduce/lib/*:$HADOOP_HOME/share/hadoop/mapreduce/*:$HADOOP_HOME/share/hadoop/tools/lib/*"

ENV PYSPARK_PYTHON python3
ENV PYSPARK_DRIVER_PYTHON=python3

ENV PATH $PATH:$JAVA_HOME/bin:$HADOOP_HOME/bin:$SPARK_HOME/bin

# Conda envs
ENV CONDA_DIR=/opt/conda CONDA_VER=4.3.14
ENV PATH=$CONDA_DIR/bin:$PATH SHELL=/bin/bash LANG=C.UTF-8

# Conda
RUN set -ex \
  && apk add --no-cache bash \
  && apk add --virtual .fetch-deps --no-cache ca-certificates wget curl \
  \
  && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
  && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk \
  && apk add --virtual .conda-deps glibc-2.28-r0.apk \
  \
  && mkdir -p $CONDA_DIR  \
  && echo export PATH=$CONDA_DIR/bin:'$PATH' > /etc/profile.d/conda.sh \
  && wget https://repo.continuum.io/miniconda/Miniconda3-${CONDA_VER}-Linux-x86_64.sh -O miniconda.sh \
  && bash miniconda.sh -f -b -p $CONDA_DIR \
  && rm miniconda.sh \
  \
  && conda update conda \
  \
  # hadoop
  && curl -sL --retry 3 \
  "http://archive.apache.org/dist/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz" \
  | gunzip \
  | tar -x -C /usr/ \
  && rm -rf $HADOOP_HOME/share/doc \
  && chown -R root:root $HADOOP_HOME \
  # spark
  && curl -sL --retry 3 \
  "https://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=spark/spark-${SPARK_VERSION}/${SPARK_PACKAGE}.tgz" \
  | gunzip \
  | tar x -C /usr/ \
  && mv /usr/$SPARK_PACKAGE $SPARK_HOME \
  && chown -R root:root $SPARK_HOME \
  # cleanup
  && apk del .fetch-deps \
  # && apk del .conda-deps

  COPY config ${SPARK_HOME}/conf

# ADD KEDRO HERE

CMD ["/bin/bash"]
```

**Comment by DmitriiDeriabinQB** [comment]
@yarncraft thanks very much for your input! I've tried to reproduce your suggestions, however came across several issues:
1. Since `gcc` is required by some of the dependencies, `apk add build-base` had also to be added
2. Even with gcc installed, some of the dependencies fail to install, here is an example of `tables` error:
```
Collecting tables==3.5.1 (from kedro==0.14.3->-r /tmp/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/c6/e6/38cdcdc501ff889ea1e60bd5ef61d0573f73606f4dd0169786fd991c6b70/tables-3.5.1.tar.gz (8.3MB)
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: /tmp/H5close6_4a491o.c:1:1: warning: return type defaults to 'int' [-Wimplicit-int]
     main (int argc, char **argv) {
     ^~~~
    /tmp/H5close6_4a491o.c: In function 'main':
    /tmp/H5close6_4a491o.c:2:5: warning: implicit declaration of function 'H5close' [-Wimplicit-function-declaration]
         H5close();
         ^~~~~~~
    /usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lhdf5
    collect2: error: ld returned 1 exit status
    * Using Python 3.6.8 (default, Jun 27 2019, 22:58:47)
    * USE_PKGCONFIG: False
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-zug7cx2o/tables/
```
3. It turns out `apk` fetches the packages via http (see issue gliderlabs/docker-alpine#184) instead of https, which poses a significant security risk for any production system using kedro.

**Comment by yetudada** [comment]
@yarncraft You've been great to work with on the Kedro side. @DmitriiDeriabinQB is looking into this for you. Thank you so much for the suggestion!

**Comment by yarncraft** [comment]
Dear @DmitriiDeriabinQB , the second issue is likely to be resolved by updating setuptools like so:
`pip install --upgrade setuptools`
(Other cases where this failure is resolved by this can be found here https://github.com/googleapis/google-cloud-python/issues/3884 and  here https://github.com/facebook/prophet/issues/418 )

Regarding the third annotation I completely agree and I am astonished as Alpine is in wide production use all over the world. I hope they will resolve it rather sooner than later! 

Last but not least, the existing Dockerfile could potentially be slimmed down using the _new_ Multi Staged Builds. A tool like https://github.com/wagoodman/dive can help you discover potential image bloat. 

Thanks for the feedback and success with further work on the project!
