### ISSUE TITLE
[KED-914] Image analysis using dive

### ISSUE THREAD

**Issue by DmitriiDeriabinQB** [quantumblacklabs/kedro-docker#8]
## Description
Investigate feasibility of [dive](https://github.com/wagoodman/dive) as per @yarncraft's suggestion in #5.

## Context
`dive` can be integrated into CI to perform image default image efficiency.

## Possible Implementation
Integration of `dive` into e2e tests.

**Comment by lorenabalan** [comment]
I've updated the title with our internal ticket number to keep track of this more easily. :)
